### PR TITLE
Add fuzzing and fix crashers.

### PR DESCRIPTION
**Pull request by stevenjohnstone**
The output of strings.ToLower can have less bytes than the input.
There are valid utf8 strings which demonstrate this which could be
entered as potential passwords which would cause an out of bounds
slice access in the dictionary match code.

Fixed issue in go 1.10 test code for adjcmatrix.go to make sure
the tests passed cleanly.

### CODE REVIEW

**Comment by dcormier** [comment]
Hey @nbutton23, it would be nice to get this merged in.

**Comment by nbutton23** [comment]
I have some free time coming up later this week and I plan on spending some time looking at this PR and anothers. Plus I want to fix some other things that I know about.  

Sorry for how long it took to respond to this.

**Comment by nbutton23** [comment]
Should the `fuzz/workdir` be checked in?

**Comment by stevenjohnstone** [comment]
It's good to have a fuzz corpus to speed up future runs

**Pull request merged**
